#pragma once
// GENERATED. Do not edit: the source of truth is the neutral model, and the
// spelling is decided in generator/cpp/ (plan-generacion-cpp.md).

#include "lv/core/obj.hpp"
#include "lv/draw/draw_buf.hpp"
#include "lv/enums.hpp"
#include "lv/fwd.hpp"
#include "lv/types.hpp"
#include "lvgl.h"
#include <cstdint>

namespace lv {

#if LV_USE_SNAPSHOT
/**
 * Take snapshot for object with its children, create the draw buffer as needed.
 * @param obj  the object to generate snapshot.
 * @param cf  color format for generated image.
 * @return a pointer to an draw buffer containing snapshot image, or NULL if failed.
 * @see lv_snapshot_take
 */
inline DrawBuf snapshot_take(Obj obj, ColorFormat cf) noexcept { return DrawBuf(lv_snapshot_take(obj.raw(), static_cast<lv_color_format_t>(cf))); }

/**
 * Create a draw buffer to store the snapshot image for object.
 * @param obj  the object to generate snapshot.
 * @param cf  color format for generated image.
 * @return a pointer to an draw buffer ready for taking snapshot, or NULL if failed.
 * @see lv_snapshot_create_draw_buf
 */
inline DrawBuf snapshot_create_draw_buf(Obj obj, ColorFormat cf) noexcept { return DrawBuf(lv_snapshot_create_draw_buf(obj.raw(), static_cast<lv_color_format_t>(cf))); }

/**
 * Reshape the draw buffer to prepare for taking snapshot for obj.
 * This is usually used to check if the existing draw buffer is enough for
 * obj snapshot. If return LV_RESULT_INVALID, you should create a new one.
 * @param draw_buf  the draw buffer to reshape.
 * @param obj  the object to generate snapshot.
 * @see lv_snapshot_reshape_draw_buf
 */
inline Result snapshot_reshape_draw_buf(Obj obj, DrawBuf draw_buf) noexcept { return static_cast<Result>(lv_snapshot_reshape_draw_buf(obj.raw(), draw_buf.raw())); }

/**
 * Take snapshot for object with its children, save image info to provided buffer.
 * @param obj  the object to generate snapshot.
 * @param cf  color format for new snapshot image. It could differ with cf of `draw_buf` as long as the new cf will fit in.
 * @param draw_buf  the draw buffer to store the image result. It's reshaped automatically.
 * @return LV_RESULT_OK on success, LV_RESULT_INVALID on error.
 * @see lv_snapshot_take_to_draw_buf
 */
inline Result snapshot_take_to_draw_buf(Obj obj, ColorFormat cf, DrawBuf draw_buf) noexcept { return static_cast<Result>(lv_snapshot_take_to_draw_buf(obj.raw(), static_cast<lv_color_format_t>(cf), draw_buf.raw())); }

/**
 * @param dsc  the image descriptor generated by lv_snapshot_take.
 * @see lv_snapshot_free
 */
inline void snapshot_free(lv_image_dsc_t* dsc) noexcept { lv_snapshot_free(dsc); }

/**
 * Take snapshot for object with its children, save image info to provided buffer.
 * @param obj  the object to generate snapshot.
 * @param cf  color format for generated image.
 * @param dsc  image descriptor to store the image result.
 * @param buf  the buffer to store image data. It must meet align requirement.
 * @param buf_size  provided buffer size in bytes.
 * @return LV_RESULT_OK on success, LV_RESULT_INVALID on error.
 * @see lv_snapshot_take_to_buf
 */
inline Result snapshot_take_to_buf(Obj obj, ColorFormat cf, lv_image_dsc_t* dsc, void* buf, uint32_t buf_size) noexcept { return static_cast<Result>(lv_snapshot_take_to_buf(obj.raw(), static_cast<lv_color_format_t>(cf), dsc, buf, buf_size)); }
#endif // LV_USE_SNAPSHOT

} // namespace lv
